### ISSUE TITLE
[Multiplayer] Display rounds

### ISSUE THREAD

**Issue by AntoninTripes** [Vixen51/rbm#141]
**Is your feature request related to a problem? Please describe.**
During the multiplayer cup I don't see how many rounds we've played and how many are left

**Describe the solution you'd like**
Display rounds clearly in the UI

**Comment by AntoninTripes** [comment]
Non-essential for _RELAUNCH_ milestone, but important for live races and livestreams

**Comment by Vixen51** [comment]
Done in CL4493

**Comment by AntoninTripes** [comment]
Is it possible for all elements to be centered?

- Currently some elements are centered and some are right-aligned
- It's going to look more polished if all elements are centered

<img width="376" height="273" alt="Image" src="https://github.com/user-attachments/assets/a45eaef5-a3e7-4e6d-ba8e-b677805b3094" />

<img width="379" height="282" alt="Image" src="https://github.com/user-attachments/assets/c5928c8c-ec2d-44d0-9599-8c7281686dac" />

**Comment by AntoninTripes** [comment]
We should consider implications of this when finishing a big race, maybe it's fine? Just noting it down for now:

- I "abandoned" a custom cup by leaving while the second track of 74 was on and I can still see this in the lobby when I returned
- Should be cleared on entering the lobby?

<img width="2551" height="1429" alt="Image" src="https://github.com/user-attachments/assets/0345c7be-b899-4b8a-8edb-6464aae93ae5" />

**Comment by Vixen51** [comment]
CL4559
